<div class="w auto">
    <div class="crumbs-nav"><a href="<?php echo $this->di['sysconfig']['siteUrl'];?>">首页</a>
        <em>></em><a href="/user/index">云朵账户</a>
        <em>></em><a href="/user/passwdedit">修改密码</a>
    </div>
    <div class="content ovh">

        <?php $this->partial("common/nav") ?>

        <div class="main fl dib">
            <div class="info-tit rel">
                <h2 class="tit dib">修改密码</h2>
                <div class="tips-suc-pop abs tac dn" id="flash-msg"></div>
                <div class="tips-suc-pop abs tac dn" id="tips-suc-popup">
                    <img class="vam" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/pwok.png" alt="新密码设置成功">新密码设置成功！
                </div>
            </div>
            <div class="myinfo change-pw">
                <form action="" method="post">
                    <div class="reg-row rel">
                        <label class="tit"></label>
              <span>为保障账号安全，我们需要您进行安全确认。发确认短信到手机
                <strong><?php echo substr_replace($this->session->get('uinfo')['mobile'], '****', 4, -3);?></strong>
              </span>
                    </div>
                    <div class="reg-row rel">
                        <label class="tit">短信验证码</label>
                        <input type="text" class="input input-text" id="captcha">
                        <input type="button" class="abs btn getcode bd-n" value="获取验证码" id="btn-send-captcha">
                        <span class="tips tips-suc" style="display: none;"></span>
                        <span class="tips-error" style="display: none;" id="tips-error-captcha"></span>
                    </div>
                    <div class="reg-row rel">
                        <label class="tit">新密码</label>
                        <input type="password" class="input input-text" id="password">
                        <span class="tips-error" style="display: none;" id="tips-error-passwd"></span>
                        <span class="tips tips-suc" style="display: none;" id="tips-suc-passwd"></span>
                        <p class="pw-lv abs">
                            <span class="pass-high" id="pwd-weak">弱</span>
                            <span class="pass-low" id="pwd-mid">中</span>
                            <span class="pass-low" id="pwd-strong">强</span>
                        </p>
                    </div>
                    <div class="reg-row rel">
                        <label class="tit">重复新密码</label>
                        <input type="password" class="input input-text" id="repwd">
                        <span class="tips tips-error" style="display: none;" id="tips-error-repwd">请重复输入密码</span>
                        <span class="tips tips-suc" style="display: none;" id="tips-suc-repwd"></span>
                    </div>
                    <div class="reg-row dn" id="bk-pic-captcha">
                        <label class="tit">验证码</label>
                        <input type="text" class="input input-text input-ver-code" id="codeImg">
                        <img class="ver-code-img" src="/captcha/getCode" alt="图片验证码" onclick="this.src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">
                        <span class="tips tips-ver-code"><a class="tdn" href="javascript:void(0);" onclick="document.getElementById('pic-captcha').src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">看不清楚？换张图片</a></span>
                        <span class="tips tips-suc dn"></span>
                        <span class="tips-error dn" id="tips-error-codeImg">验证码错误</span>
                    </div>
                    <div class="reg-row">
                        <label class="tit"></label>
                        <input type="hidden"  name="regtype" value='9' id="regtype">
                        <input type="button" class="btn btn-grey bd-n" value="确定修改" id="btn-change-pwd" disabled="true">
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("modules/passwdedit/main");

</script>