<header class="mb-my">
    <nav>
        <a class="goback fl" href="javascript:history.go(-1);">
            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/btn-back.png" alt="goback">
        </a>
        <p class="nav-tit">忘记密码</p>
    </nav>
</header>

<div class="tips-suc-pop tac dn" id="flash-msg"></div>

<div class="wrap mb-w auto">
    <div class="reg-box">
        <form action="" method="post">
            <div class="reg-row">
                <input type="text" class="input input-text" placeholder="请输入手机号" id="mobile">
                <span class="tips tips-error dn" id="tips-error-mobile"></span>
            </div>
            <div class="reg-row rel">
                <input type="text" class="input input-text" placeholder="请输入验证码" id="captcha">
                <input type="button" class="abs btn getcode bd-none" value="获取验证码" id="btn-send-captcha">
                <span class="tips tips-error dn" id="tips-error-captcha"></span>
            </div>
            <div class="reg-row dn" id="bk-pic-captcha">
                <input type="text" class="input input-text input-ver-code" placeholder="请输入验证码" id="codeImg">
                <img class="ver-code-img" src="/captcha/getCode" alt="图片验证码" onclick="this.src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">
                <p><span class="tips tips-error dn" id="tips-error-codeImg">验证码错误</span></p>
            </div>
            <div class="reg-row">
                <input type="hidden"  name="regtype" value='7' id="regType">
                <input type="button" class="btn btn-grey bd-none" value="下一步" id="btn-next">
            </div>
        </form>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/reset/main");

</script>