    <!-- 公共头部开始 -->
    <header class="header bb">
      <nav class="nav tac rel fix">
        <a class="nav-menu" href="<?php echo $this->di['sysconfig']['mobileUrl'];?>">
          <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/nav-home.png" alt="nav-home">
        </a>
        <p class="nav-tit">我的云朵</p>
        <div class="nav-right">
          <a class="nav-cart order" href="<?php echo $this->di['sysconfig']['mobiMallUrl'];?>ng/#/cart"><img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/nav-cart.png" alt="nav-cart">
          </a>
        </div>
      </nav>
    </header>
    <!-- 公共头部结束 -->

    <!--[/include]-->
    <!-- 正文主体开始 -->
  <div id="bodyWrap">
    <div class="my-cloud-hd">
      <div class="mb-w auto">
        <div class="hd-avatar">
          <img id="hd-avatar-img" class="hd-avatar-img" src="<?php if(!$userinfo['u_pic']):echo $this->di['sysconfig']['staticServer'].'images/avatar.jpg'?><?php else:echo $userinfo['u_pic'];?><?php endif;?>" alt="avatar-placeholder">
        </div>
        <div class="hd-main">
          <div class="hd-name">
            <div id="name-edit" class="name-edit">
              <span id="name-edit-text"><?php echo (empty($userinfo['u_name']) && $userinfo['u_name'] != '0') ? '':$userinfo['u_name'];?></span> <a href="javascript:void(0);" title="edit"><img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/my-edit.png" alt="my-edit"></a>
            </div>
            <div id="edit-input-wrap" class="rel dn">
              <input id="edit-input" class="edit-input" type="text" name="" value="<?php echo (empty($userinfo['u_name']) && $userinfo['u_name'] != '0') ? '':$userinfo['u_name'];?>">
              <!-- <a id="edit-close" class="edit-close" href="javascript:void(0)" title="close"></a> -->
            </div>
          </div>
          <div class="hd-rank">等级：<span class="rank rank-orange">LV<?php echo $userinfo['u_level'];?> 级</span></div>
          <div class="hd-coin">云币：<?php echo $userinfo['uw_coins'];?> 枚</div>
        </div>
      </div>
    </div>
    <div class="my-cloud-module">
      <div class="mb-w auto">
        <div class="row">
          <div class="nav-row my-order"></div>
          <div class="text-row">我的订单 <a href="<?php echo $this->di['sysconfig']['mobiMallUrl'];?>ng/#/order" title="查看全部订单">查看全部订单 <div class="arrows-right"></div></a></div>
        </div>

        <div class="row">
          <div class="nav-row order-service"></div>
          <div class="text-row bdn">售后订单 <a href="<?php echo $this->di['sysconfig']['mobiMallUrl'];?>ng/#/support" title="查看全部"><span id="sup-cnt" class="badge"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<div class="arrows-right"></div></a></div>
        </div>
      </div>
    </div>
  <!--  <div class="my-cloud-module">
      <div class="mb-w auto">
        <div class="row">
          <div class="nav-row my-device"></div>
          <div class="text-row bdn">我的设备 <a href="javascript:void(0);" title="查看全部">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<div class="arrows-right"></div></a></div>
        </div>
         <div class="row">
          <div class="nav-row my-coupons"></div>
          <div class="text-row bdn">优惠券 <a href="<?php echo $this->di['sysconfig']['mallServer'];?>coupons" title="查看全部">有4张优惠券即将过期 <div class="arrows-right"></div></a></div>
        </div>
      </div>
    </div>-->
    <div class="my-cloud-module">
      <div class="mb-w auto">
        <div class="row">
          <div class="nav-row my-address"></div>
          <div class="text-row">收货地址 <a href="<?php echo $this->di['sysconfig']['mobiMallUrl'];?>ng/#/addr" title="查看全部">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<div class="arrows-right"></div></a></div>
        </div>
        <div class="row">
          <div class="nav-row my-password"></div>
          <div class="text-row bdn">修改密码 <a href="/user/passwdedit" title="查看全部"><div class="arrows-right fr"></div></a></div>
        </div>
      </div>
    </div>
    <div id="logout" class="btn-quit">
      <a class="quit" href="javascript:void(0);" title="退出登录">退出登录</a>
    </div>

    <!--修改头像时的图片上传表单
    <form id="upload-img-form" action="/user/uploadPhoto" method="post" enctype="multipart/form-data" target="upframe">
        <input type="file" style="position: absolute; width: 10px; filter: alpha(opacity=0);opacity: 0; top: 0px; display: none" class="input" name="upfile" size="20" id="upfile">
    </form>

    //iframe用于文件上传的无刷新
   <iframe id="upframe" name="upframe" src="" style="display:none;">
   </iframe>
  </div>
  -->

<!--头像裁剪界面, 开始
  <div class="avatar-btn" id="avatar-sub" style="display:none; margin-top:100px">
      <form id="avatar-form" action="/user/cropPhoto" method="post">
          <input type="hidden" id="nor-w" value=""/>
          <input type="hidden" id="nor-h" value=""/>
          <input type="hidden" name="x1" value="0" id="x1" />
          <input type="hidden" name="y1" value="0" id="y1" />
          <input type="hidden" name="x2" value="100" id="x2" />
          <input type="hidden" name="y2" value="100" id="y2" />
          <input type="hidden" name="w" value="100" id="w" />
          <input type="hidden" name="h" value="100" id="h" />
          <a href="javascript:void(0)" class="btn tdn btn-blue btn-save" id="save-thumb">保存</a>
          <a href="/user/index" class="btn tdn btn-quit">取消</a>
      </form>
  </div>

  <div id="change-avatar" class="change-avatar">
    <div class="mask">
      <div id="cut-box" class="cut-box"></div>
    </div>
    <div class="fix-btn">
      <a id="can-crop" href="javascript:void(0);">取消</a>
      <a id="sav-crop" href="javascript:void(0);">裁剪</a>
    </div>
  </div>
  头像裁剪界面, 结束-->

    <!-- 正文主体结束 -->
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>
document.getElementById('logout').onclick = function(){
    location.href = '/index/logout';
};

seajs.config({
    base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/"
});

$(function () {
    var oldName = $("#edit-input").val();
    $("#edit-input").blur(function () {
        var nickName = $("#edit-input").val();
        if (!nickName) {
            alert('昵称不能为空');
            $("#edit-input").val(oldName);
            $("#edit-input-wrap").addClass("dn");
            $("#name-edit").removeClass("dn");
            return;
        }
        if (nickName == oldName) {
            $("#edit-input-wrap").addClass("dn");
            $("#name-edit").removeClass("dn");
            return;
        }

        function removeHTMLTag(str) {
            str = str.replace(/<\/?[^>]*>/g,''); //去除HTML tag
            str = str.replace(/[ | ]*\n/g,'\n'); //去除行尾空白
            //str = str.replace(/\n[\s| | ]*\r/g,'\n'); //去除多余空行
            str=str.replace(/&nbsp;/ig,'');//去掉&nbsp;
            return str;
        }

        $.ajax({
            type: 'POST',
            url: '/user/editName',
            dataType: 'json',
            data: "name="+nickName,
            success: function(msg) {
                if(msg.ret == 1){
                    oldName = $("#edit-input").val();
                    $("#name-edit-text").html(removeHTMLTag(oldName));
                    $("#edit-input-wrap").addClass("dn");
                    $("#name-edit").removeClass("dn");
                    //setTimeout(function(){window.location.href = '';}, 5000);
                }
                else
                {
                    alert(msg.msg.name.msg);
                    $("#edit-input").val(oldName);
                    $("#edit-input-wrap").addClass("dn");
                    $("#name-edit").removeClass("dn");
                }
            },
            error:function(){
                alert('服务器出现异常，请稍候重试');
                $("#edit-input").val(oldName);
                $("#edit-input-wrap").addClass("dn");
                $("#name-edit").removeClass("dn");
            }
        });
    });

    $("#name-edit").click(function () {
        $("#name-edit").addClass("dn");
        $("#edit-input-wrap").removeClass("dn");
        $("#edit-input").focus();
    });

    $("#edit-close").click(function () {
        $("#edit-input").val("");
        $("#edit-input").focus();
    });

    // $('#hd-avatar-img').on('click', function(){
    //     $('#upfile').click();
    // });

    // $("body").on("change", "#upfile", function () {
    //     //默认submit()是不会阻塞的, 所以需要绑定iframe的onload事件
    //     $("#upload-img-form").submit();
    //     var iframe = document.getElementById("upframe");

    //     if (iframe.attachEvent){
    //         iframe.attachEvent("onload", fraLoaded);
    //     } else {
    //         iframe.onload = fraLoaded;
    //     }

    //     function fraLoaded () {
    //         var resJsonStr = iframe.contentWindow.document.getElementsByTagName("body")[0].innerHTML;
    //         //alert($.parseJSON(resJsonStr));
    //         var msg = $.parseJSON(resJsonStr);
    //         if (msg) {
    //                 if(msg.ret == 1){
    //                     seajs.use("modules/mobile/userindex", function (crop) {
    //                         $("#bodyWrap").css("display", "none");
    //                         $("header").css("display", "none");
    //                         $("footer").css("display", "none");
    //                         $("#change-avatar").css("display", "block");
    //                         crop.myCrop.cropInit(100, "cut-box");
    //                         $("#change-avatar").css("background", "url(" + msg.msg + ") no-repeat");
    //                         $("#cut-box").css("background", "url(" + msg.msg + ") no-repeat");
    //                         $("#sav-crop").click(cropFin);
    //                         $("#can-crop").click(cropCan);

    //                         function cropFin() {
    //                             $('#x1').val(crop.myCrop.bound[1]);
    //                             $('#y1').val(crop.myCrop.bound[4]);
    //                             $('#x2').val(crop.myCrop.bound[3]);
    //                             $('#y2').val(crop.myCrop.bound[2]);
    //                             $('#w').val(crop.myCrop.arealen);
    //                             $('#h').val(crop.myCrop.arealen);
    //                             $('#avatar-form').submit();
    //                         }

    //                         function cropCan () {
    //                             $("#change-avatar").css("display", "none");
    //                             $("#bodyWrap").css("display", "block");
    //                             $("header").css("display", "block");
    //                             $("footer").css("display", "block");
    //                         }
    //                     });
    //                 }
    //                 else{
    //                     alert(msg.msg);
    //                 }
    //         } else {
    //             alert("服务器上传图片失败.");
    //         }
    //     }
    // });
});
</script>
