<header class="mb-my">
    <nav>
        <a class="goback fl" href="javascript:history.go(-1);">
            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/btn-back.png" alt="goback">
        </a>
        <p class="nav-tit">修改密码</p>
    </nav>
</header>

<div class="tips-suc-pop tac dn" id="flash-msg"></div>

<div class="wrap mb-w auto">
    <div class="reg-box">
        <form action="" method="post">
            <div class="reg-row rel">
                <input type="text" class="input input-text" placeholder="请输入验证码" id="captcha">
                <input type="button" class="abs btn getcode bd-none" value="获取验证码" id="btn-send-captcha">
                <span class="tips tips-error dn" id="tips-error-captcha">输入错误，请重新获取验证码</span>
            </div>
            <div class="reg-row rel">
                <input type="password" class="input input-text" placeholder="请输入新密码" id="password">
                <span class="tips tips-error dn" id="tips-error-passwd"></span>
                <p class="pw-lv fr">
                    <span class="pass-high" id="pwd-weak">弱</span>
                    <span class="pass-low" id="pwd-mid">中</span>
                    <span class="pass-low" id="pwd-strong">强</span>
                </p>
            </div>
            <div class="reg-row">
                <input type="password" class="input input-text" placeholder="请重复新密码" id="repwd">
                <span class="tips tips-error dn" id="tips-error-repwd">两次密码不一样</span>
            </div>
            <div class="reg-row dn" id="bk-pic-captcha">
                <input type="text" class="input input-text input-ver-code" placeholder="请输入验证码" id="codeImg">
                <img class="ver-code-img" src="/captcha/getCode" alt="图片验证码" onclick="this.src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">
                <p><span class="tips tips-error dn" id="tips-error-codeImg">验证码错误</span></p>
            </div>
            <div class="reg-row">
                <input type="hidden" value="9" id="regtype" />
                <input type="button" class="btn btn-grey bd-none" value="确定修改" id="btn-change-pwd">
            </div>
        </form>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "zepto" : "spm_modules/zepto/1.1.3/dist/zepto.js",
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/mobile/passwdedit");

</script>