<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="keywords" content="云朵儿童安全鞋，云朵儿童，云朵安全，yunduokids,yunduo儿童安全鞋，云朵官方网站，云朵智能穿戴设备，儿童打拐，儿童安全">
    <meta name="description" content="云朵儿童安全鞋，是一款针对儿童与家长设计的软硬件结合的产品，通过童鞋内置设备与智能手机APP连接，实现与儿童安全鞋轻松关联，准确定位儿童安全鞋穿着者的所在位置。帮助家长及时了解小孩的出行情况。通过云朵APP任务设置，鼓励用户更注重家庭情感及宝宝养成。">
    <title>错误--云朵儿童安全官网</title>
    <link rel="stylesheet" href="<?php echo $this->di['sysconfig']['staticServer'];?>css/my.css">
    <link rel="shortcut icon" href="/favicon.ico">
    <!--[if lt IE 9]><script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/html5.js"></script><![endif]-->
</head>

<body style="background: #f3f3f3;">

<header class="hd-login">
    <nav>
        <div class="nav">
            <div class="w auto">
                <a href="http://www.yunduo.com">
                    <img class="vam" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/logo.png" alt="logo">
                </a>
            </div>
        </div>
    </nav>
</header>

<div class="wrap">
    <div class="reg fz14">
        <div class="tac">
            <div class="reg-suc-tips">
                <p class="suc-tit">
                    <img src="<?php echo $this->di['sysconfig']['staticServer'];?><?php echo ($errCode == 2 || $errCode == 6)? 'images/link-ok.png': 'images/link-error.jpg'?>" alt="error">
                </p>
                <p class="suc-tit"><?php echo $error;?></p>
                <p>
                    <strong id="seconds-remain">5</strong>秒</strong>后，我们将为您跳转到<a href="<?php echo $url;?>" class="color"><?php echo $title?></a>
                </p>
            </div>
        </div>
    </div>
</div>

<footer>
    <address>Copyright©2014 版权归属 云朵网络有限公司
      <span class="cnzz">
          <span class="cnzz">
              <script type="text/javascript">
                  var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
                  document.write(unescape("%3Cspan id='cnzz_stat_icon_1000458188'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1000458188' type='text/javascript'%3E%3C/script%3E"));
              </script>
          </span>
      </span>
        <p>闽ICP备14002317号-1</p>
    </address>
</footer>

<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/jquery/1.11.1/jquery.min.js"></script>
<script>

    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/utils/jump", function(jump){
        jump.errReturn('/user/index');
    });

</script>
</body>

</html>