<header class="mb-my">
    <nav>
        <a class="goback fl" href="javascript:history.go(-1);">
            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/btn-back.png" alt="goback">
        </a>
        <p class="nav-tit">登录</p>
        <a class="nav-login fr" href="/register">注册</a>
    </nav>
</header>

<div class="tips-suc-pop tac dn" id="flash-msg"></div>

<div class="wrap mb-w auto">
    <div class="reg-box">
        <form action="" method="post">
            <div class="reg-row">
                <input type="text" class="input input-text" placeholder="请输入手机号" id="mobile">
                <span class="tips tips-error dn" id="tips-error-mobile"></span>
            </div>

            <div class="reg-row">
                <input type="password" class="input input-text" placeholder="请输入密码" id="passwd">
                <span class="tips tips-error dn" id="tips-error-passwd"></span>
            </div>
            <div class="reg-row">
                <input type="hidden" name="backurl" value="<?php echo !empty($backurl) ? $backurl : ''; ?>">
                <input type="hidden" name="siteId" value="<?php echo !empty($siteId) ? $siteId : ''; ?>">
                <input type="button" class="btn btn-blue bd-none" value="登录" id="login-btn">
            </div>
        </form>
    </div>
    <div class="login-other">
        <p>其他方式登录：<a href="/index/wboauth" class="dib login-wb"></a><a href="/index/qqoauth" class="dib login-qq"></a><a href="/index/alipay" class="dib login-zfb"></a><a class="color tdn fr" href="/reset"> 忘记密码？</a></p>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/login/main");

</script>