<header class="mb-my">
    <nav>
        <a class="goback fl" href="javascript:history.go(-1);">
            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/btn-back.png" alt="goback">
        </a>
        <p class="nav-tit">注册</p>
    </nav>
</header>

<div class="wrap mb-w auto">
    <div class="register-success tac">
        <p class="tit">
            <img class="vam" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mobile/reg-suc.png" alt="注册">注册成功</p>
        <p class="desc">
            <span><strong id="seconds-remain">5</strong><strong>秒</strong>后我们将为您跳转到<a class="tdn color" href="#"> 云朵首页</a></span>
        </p>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/mobile/success");

</script>