<div class="wrap">
    <div class="reg fz14">
        <div class="account reg-pw">
            <h1 class="tit">忘记密码</h1>
            <p class="tit-desc">
                <span class="color">验证手机号</span>
                <em>></em>
                <span>设置新密码</span>
                <em>></em>
                <span>修改成功</span>
            </p>
        </div>

        <div class="tips-suc-pop dn tac " id="flash-msg"></div>

        <div class="reg-box pw-box">
            <form action="" method="post">
                <div class="reg-row center rel">
                    <label class="tit">请输入手机号</label>
                    <input type="text" class="input input-text" id="mobile">
                    <span class="tips tips-error dn" id="tips-error-mobile">手机号码格式错误</span>
                    <span class="tips tips-error dn">请输入手机号码</span>
                    <span class="tips tips-suc dn" id="tips-suc-mobile"></span>
                </div>
                <div class="reg-row center rel">
                    <label class="tit">短信验证码</label>
                    <input type="text" class="input input-text" id="captcha">
                    <input type="button" class="abs btn getcode bd-n" value="获取验证码" id="btn-send-captcha">
                    <span class="tips-error dn" id="tips-error-captcha">输入错误，请重新获取验证码</span>
                </div>
                <div class="reg-row dn" id="bk-pic-captcha">
                    <label class="tit">验证码</label>
                    <input type="text" class="input input-text input-ver-code" id="codeImg">
                    <img class="ver-code-img" src="/captcha/getCode" alt="图片验证码" onclick="javascript:this.src='/captcha/getCode?tm='+Math.random();">
                    <span class="tips tips-ver-code"><a class="tdn" href="javascript:void(0)">看不清楚？换张图片</a></span>
                    <span class="tips tips-suc dn"></span>
                    <span class="tips-error dn" id="tips-error-codeImg"></span>
                </div>
                <div class="reg-row">
                    <label class="tit"></label>
                    <input type="hidden"  name="regtype" value='7' id="regType">
                    <input type="button" class="btn btn-grey bd-n" value="下一步" id="btn-next">
                </div>
            </form>
        </div>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("modules/reset/main");

</script>