<div class="w auto">
    <div class="crumbs-nav"><a href="<?php echo $this->di['sysconfig']['siteUrl'];?>">首页</a>
        <em>></em><a href="/user/index">云朵账户</a>
        <em>></em><a href="/user/index">个人中心</a>
        <em>></em><a href="/email/index">更改邮箱</a>
    </div>
    <div class="content ovh">
        <div class="side fl dib">
            <h2 class="tit">云朵账户</h2>
            <ul>
                <li class="cur"><a href="/user/index" class="tdn">个人中心</a>
                </li>
                <li><a href="/user/accountbind" class="tdn">账号绑定</a>
                </li>
                <li><a href="/user/passwdedit" class="tdn">修改密码</a>
                </li>
            </ul>
        </div>
        <div class="main fl dib">
            <div class="info-tit rel">
                <h2 class="tit dib">更改邮箱</h2>
                <div class="tips-suc-pop abs tac dn" id="flash-msg"></div>
            </div>
            <div class="myinfo">
                <div class="process-status">
                    <span class="dib pro-green">1</span>
                    <span class="dib pro-line-grey green"></span>
                    <span class="dib pro-grey green">2</span>
                    <span class="dib pro-line-grey"></span>
                    <span class="dib pro-grey">3</span>
                </div>
                <div class="process-desc">
                    <p class="dib green">验证身份</p>
                    <p class="dib grey green">输入新邮箱</p>
                    <p class="dib grey">更改成功</p>
                </div>
            </div>
            <div class="ensure">
                <form action="" method="post">
                    <div class="reg-row rel">
                        <label class="tit">当前邮箱</label>
                        <span class="desc"><?php echo $userinfo['u_email'];?></span>
                    </div>
                    <div class="reg-row rel">
                        <label class="tit">请输入新邮箱</label>
                        <input type="text" class="input input-text" id="email">
                        <span class="tips tips-suc dn"></span>
                        <span class="tips tips-error dn" id="tips-error-email"></span>
                    </div>
                    <div class="reg-row">
                        <label class="tit"></label>
                        <input type="button" class="btn btn-blue bd-n" value="确定" id="email-confirm">
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("modules/email/main");

</script>