<div class="w auto">
    <div class="crumbs-nav"><a href="<?php echo $this->di['sysconfig']['siteUrl'];?>">首页</a>
        <em>></em><a href="/user/index">云朵账户</a>
        <em>></em><a href="/user/index">个人中心</a>
        <em>></em><a href="/email/index">更改邮箱</a>
    </div>
    <div class="content ovh">
        <div class="side fl dib">
            <h2 class="tit">云朵账户</h2>
            <ul>
                <li class="cur"><a href="/user/index" class="tdn">个人中心</a>
                </li>
                <li><a href="/user/accountbind" class="tdn">账号绑定</a>
                </li>
                <li><a href="/user/passwdedit" class="tdn">修改密码</a>
                </li>
            </ul>
        </div>
        <div class="main fl dib">
            <div class="info-tit rel">
                <h2 class="tit dib">更改邮箱</h2>
                <div class="tips-suc-pop abs tac dn" id="flash-msg"></div>
            </div>
            <div class="myinfo">
                <div class="process-status">
                    <span class="dib pro-green">1</span>
                    <span class="dib pro-line-grey"></span>
                    <span class="dib pro-grey">2</span>
                    <span class="dib pro-line-grey"></span>
                    <span class="dib pro-grey">3</span>
                </div>
                <div class="process-desc">
                    <p class="dib green">验证身份</p>
                    <p class="dib grey">输入新邮箱</p>
                    <p class="dib grey">更改成功</p>
                </div>
            </div>
            <div class="ensure">
                <p>为保障账号安全，我们需要您进行安全确认。发确认短信到我的手机 <strong><?php echo substr_replace($this->session->get('uinfo')['mobile'], '****', 4, -3);?></strong>
                </p>
                <form action="" method="post">
                    <div class="reg-row rel">
                        <input type="text" class="input input-text" placeholder="请输入验证码" id="captcha">
                        <input type="button" class="abs btn getcode bd-n" value="获取验证码" id="btn-send-captcha">
                        <span class="tips tips-suc dn" id="tips-suc-captcha"></span>
                        <span class="tips-error dn" id="tips-error-captcha"></span>
                    </div>
                    <div class="reg-row dn" id="bk-pic-captcha">
                        <input type="text" class="input input-text input-ver-code" id="codeImg">
                        <img class="ver-code-img" src="/captcha/getCode" alt="图片验证码" onclick="this.src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">
                        <span class="tips tips-ver-code"><a class="tdn" href="javascript:void(0);" onclick="document.getElementById('pic-captcha').src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">看不清楚？换张图片</a></span>
                        <span class="tips tips-suc dn"></span>
                        <span class="tips-error dn" id="tips-error-codeImg">验证码错误</span>
                    </div>
                    <div class="reg-row">
                        <input type="hidden" value="11" id="regtype">
                        <input type="button" class="btn btn-blue bd-n" value="下一步" id="email-next">
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("modules/email/main");

</script>