<div class="w auto">
    <div class="crumbs-nav"><a href="<?php echo $this->di['sysconfig']['siteUrl'];?>">首页</a>
        <em>></em><a href="/user/index">云朵账户</a>
        <em>></em><a href="/user/index">个人中心</a>
        <em>></em><a href="/email/index">更改邮箱</a>
    </div>
    <div class="content ovh">
        <div class="side fl dib">
            <h2 class="tit">云朵账户</h2>
            <ul>
                <li class="cur"><a href="/user/index" class="tdn">个人中心</a>
                </li>
                <li><a href="/user/accountbind" class="tdn">账号绑定</a>
                </li>
                <li><a href="/user/passwdedit" class="tdn">修改密码</a>
                </li>
            </ul>
        </div>
        <div class="main fl dib">
            <div class="info-tit rel">
                <h2 class="tit dib">更改邮箱</h2>
                <div class="tips-suc-pop abs tac dn" id="flash-msg"></div>
            </div>
            <div class="myinfo">
                <div class="process-status">
                    <span class="dib pro-green">1</span>
                    <span class="dib pro-line-grey green"></span>
                    <span class="dib pro-grey green">2</span>
                    <span class="dib pro-line-grey green"></span>
                    <span class="dib pro-grey green">3</span>
                </div>
                <div class="process-desc">
                    <p class="dib green">验证身份</p>
                    <p class="dib grey green">输入新邮箱</p>
                    <p class="dib grey green">更改成功</p>
                </div>
            </div>
            <div class="ensure">
                <div class="mail-suc"><img class="vam fl" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/reg-suc.png" alt="成功"><p>亲爱的<?php echo $uname;?>，我们给您的邮箱<?php echo $email;?>发送了一封验证邮件，
                        <br/>您只要点击邮件中的按钮或者链接，即可完成新邮箱的验证。</p></div>
            </div>

        </div>
    </div>
</div>