<header>
    <nav class="my-nav">
        <div class="sub-nav">
            <div class="w auto">
                <a href="<?php echo $this->di['sysconfig']['siteUrl'];?>">
                    <img class="vam" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/logo.png" alt="logo">
                </a>
            </div>
        </div>
    </nav>
</header>

<?php echo $this->getContent(); ?>

<footer>
    <address>Copyright©2015 版权归属 云朵网络有限公司
      <span class="cnzz">
          <span class="cnzz">
              <script type="text/javascript">
                  var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
                  document.write(unescape("%3Cspan id='cnzz_stat_icon_1000458188'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1000458188' type='text/javascript'%3E%3C/script%3E"));
              </script>
          </span>
      </span>
        <p>闽ICP备14002317号-1</p>
    </address>

</footer>