<div class="wrap">
    <div class="reg fz14">
        <div class="account">
            <h1 class="tit">创建一个云朵账号</h1>
            <p class="tit-desc">云朵账户能让您更方便的享受各项云朵服务。如果您已拥有云朵账户，请
                <a href="/login" class="color">点此登录</a>
            </p>
        </div>

        <div class="tips-suc-pop tac dn" id="flash-msg"></div>

        <div class="reg-box">
            <form action="" method="post">
                <div class="reg-row rel">
                    <label class="tit">
                        <em class="tips-star"></em>手机号</label>
                    <input type="text" class="input input-text" id="mobile" data="1" name="mobile"/>
                    <span class="tips tips-error" style="display: none;" id="tips-error-mobile"></span>
                    <span class="tips tips-error" style="display: none;">手机号码格式错误</span>
                    <span class="tips tips-error" style="display: none;">请输入手机号码</span>
                    <span class="tips tips-suc" style="display: none;" id="tips-suc-mobile"></span>
                </div>
                <div class="reg-row rel">
                    <label class="tit">
                        <em class="tips-star"></em>短信验证码</label>
                    <input type="text" class="input input-text" id="captcha" name="captcha" />
                    <input type="button" class="abs btn getcode bd-n" value="获取验证码" id="btn-send-captcha" >
                    <span class="tips-error" style="display: none;" id="tips-error-captcha">输入错误，请重新获取验证码</span>
                    <span class="tips tips-suc" style="display: none;" id="tips-suc-captcha"></span>
                </div>
                <div class="reg-row rel">
                    <label class="tit">
                        <em class="tips-star"></em>设置密码</label>
                    <input type="password" class="input input-text" id="password" name="password" />
                    <span class="tips tips-error" style="display: none;" id="tips-error-passwd"></span>
                    <span class="tips tips-suc" style="display: none;" id="tips-suc-passwd"></span>
                    <p class="pw-lv abs">
                        <span class="pass-high" id="pwd-weak">弱</span>
                        <span class="pass-low" id="pwd-mid">中</span>
                        <span class="pass-low" id="pwd-strong">强</span>
                    </p>
                </div>
                <div class="reg-row rel">
                    <label class="tit">
                        <em class="tips-star"></em>重复密码</label>
                    <input type="password" class="input input-text" id="confirmpass" name="repassword"/>
                    <span class="tips tips-error" style="display: none;" id="tips-error-confirmpass"></span>
                    <span class="tips tips-suc" style="display: none;" id="tips-suc-confirmpass"></span>
                </div>
                <div class="reg-row">
                    <label class="tit">常用邮箱</label>
                    <input type="text" class="input input-text" id="email" placeholder="选填" name="email" />
                    <span class="tips tips-error" style="display: none;" id="tips-error-email"></span>
                    <span class="tips tips-suc" style="display: none;" id="tips-suc-email"></span>
                    <div class="reg-row dn" id="bk-pic-captcha">
                        <label class="tit">验证码</label>
                        <input type="text" class="input input-text input-ver-code" id="codeImg">
                        <img class="ver-code-img" src="/captcha/getCode" alt="图片验证码" onclick="this.src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">
                        <span class="tips tips-ver-code"><a class="tdn" href="javascript:void(0);" onclick="document.getElementById('pic-captcha').src='/captcha/getCode?tm='+Math.random();" id="pic-captcha">看不清楚？换张图片</a></span>
                        <span class="tips tips-suc dn"></span>
                        <span class="tips-error dn" id="tips-error-codeImg">验证码错误</span>
                    </div>
                    <div class="reg-row">
                        <label class="tit"></label>
                        <div class="copyright">
                            <input type="checkbox" checked="checked" id="agree" name="agree"/>
                            <span>我已阅读并同意遵守</span>
                            <a href="/about/clause" class="color" target="_blank">网站使用条款</a> 和 <a href="/about/privacy" class="color" target="_blank">隐私条款</a>
                        </div>
                    </div>
                    <div class="reg-row">
                        <label class="tit"></label>
                        <input type="hidden"  name="regtype" value='1' id="regtype"/>
                        <input type="button" class="btn btn-blue bd-n" value="立即注册" id="reg-btn"/>
                    </div>
            </form>
        </div>
    </div>
</div>
<script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script>

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            "validator" : "utils/validator.js"
        }
    });

    seajs.use("modules/register/main");

</script>