<!DOCTYPE html>
<html lang="zh-cn">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="keywords" content="云朵儿童安全鞋，云朵儿童，云朵安全，yunduokids,yunduo儿童安全鞋，云朵官方网站，云朵智能穿戴设备，儿童打拐，儿童安全">
  <meta name="description" content="云朵儿童安全鞋，是一款针对儿童与家长设计的软硬件结合的产品，通过童鞋内置设备与智能手机APP连接，实现与儿童安全鞋轻松关联，准确定位儿童安全鞋穿着者的所在位置。帮助家长及时了解小孩的出行情况。通过云朵APP任务设置，鼓励用户更注重家庭情感及宝宝养成。">
  <title>云朵儿童安全鞋官网——云朵儿童安全鞋设备唯一官方正品销售网站。</title>
  <link rel="stylesheet" href="<?php echo $this->di['sysconfig']['staticServer'];?>css/mobile.css">
  <link rel="stylesheet" href="<?php echo $this->di['sysconfig']['staticServer'];?>css/style.css">
  <script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/zepto/zepto-rebuild.js"></script>
</head>
<body>

<?php echo $this->getContent(); ?>

    <!--[include "../include/m-footer.html"]-->
    <!-- 公共尾部开始 -->
    <footer>
      <address>
        <p class="cs-tel">客服电话：<span class="tel">400-0000-400</span></p>
        <p>Copyright©2015 版权归属 云朵网络</p>
        <p>闽ICP备14002317号-1</p>
      </address>
      <div class="view-version">
        <a href="<?php echo $this->di['sysconfig']['mobileUrl'];?>">首页</a>
        <em>|</em>
        <a href="/index/logout">登录</a>
        <em>|</em>
        <a href="<?php echo (isset($_SERVER['REQUEST_URI'])? $_SERVER['REQUEST_URI']: ''); ?>?v=p">电脑版</a>
        <em>|</em>
        <a href="#" class="to-top">返回顶部</a>
      </div>
      <div class="cnzz">
        <script type="text/javascript">
        var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
        document.write(unescape("%3Cspan id='cnzz_stat_icon_1000458188'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1000458188' type='text/javascript'%3E%3C/script%3E"));
        </script>
      </div>
    </footer>
    <!-- 公共尾部结束 -->
    <div id="backtop">
      <a href="#" class="backtop to-top"></a>
    </div>
    <!-- 返回顶部 -->
    <!--[/include]-->
  </div>
</body>

</html>

<script type="text/javascript">
$(function(){
    // 返回顶部
    $("#backtop").hide();
    $(window).scroll(function() {
      if ($(this).scrollTop() > 1) {
        $("#backtop").show();
      } else {
        $("#backtop").hide();
      }
    });
    $("#backtop a").click(function() {
        scroll(0,0);
    });
});
</script>
