<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="keywords" content="云朵儿童安全鞋，云朵儿童，云朵安全，yunduokids,yunduo儿童安全鞋，云朵官方网站，云朵智能穿戴设备，儿童打拐，儿童安全">
    <meta name="description" content="云朵儿童安全鞋，是一款针对儿童与家长设计的软硬件结合的产品，通过童鞋内置设备与智能手机APP连接，实现与儿童安全鞋轻松关联，准确定位儿童安全鞋穿着者的所在位置。帮助家长及时了解小孩的出行情况。通过云朵APP任务设置，鼓励用户更注重家庭情感及宝宝养成。">
    <title><?php if(isset($pageTitle)){echo $pageTitle;}?>--云朵儿童安全官网</title>
    <link rel="stylesheet" href="<?php echo $this->di['sysconfig']['staticServer'];?>css/my.css">
    <link rel="shortcut icon" href="/favicon.ico">
    <script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/jquery/1.11.1/jquery.min.js"></script>
    <!--[if lt IE 9]>
    <script src="<?php echo $this->di['sysconfig']['staticServer'];?>js/hooks/html5.js"></script>
    <![endif]-->
</head>

<body style="background-color: #fff">
<?php echo $this->getContent(); ?>

</body>

</html>
